name: CI

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
      - name: Build project
        run: xmake -y
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: build/windows/x64/release